services:
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: nufflearena_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=bb_user
      - POSTGRES_PASSWORD=bb_pass
      - POSTGRES_DB=bb_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - traefik-network
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8200:3100"
    container_name: nufflearena_web
    environment:
      - NODE_ENV=development
      - PORT=3100
      - NEXT_PUBLIC_API_BASE=http://localhost:8201
      - SERVER_API_BASE=http://server:8201
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/packages/ui/node_modules
      - /app/packages/game-engine/node_modules
    working_dir: /app
    command: >
      sh -c "
        pnpm install &&
        pnpm run dev:web
      "
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nufflearena.rule=Host(`nufflearena.fr`)"
      - "traefik.http.routers.nufflearena.entrypoints=websecure"
      - "traefik.http.routers.nufflearena.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nufflearena.middlewares=secure-headers@file"
      - "traefik.http.services.nufflearena.loadbalancer.server.port=3100"
      - "traefik.http.routers.nufflearena-local.rule=Host(`nufflearena.local`)"
      - "traefik.http.routers.nufflearena-local.entrypoints=web"
      - "traefik.http.services.nufflearena-local.loadbalancer.server.port=3100"
      - "traefik.docker.network=traefik-network"
    depends_on:
      - server
      - db

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: nufflearena_server
    ports:
      - "8202:8202"
      - "8201:8201"
    environment:
      - NODE_ENV=development
      - PORT=8202
      - API_PORT=8201
      - DATABASE_URL=postgresql://bb_user:bb_pass@db:5432/bb_db?schema=public
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app/apps/server
    networks:
      - traefik-network
    command: >
      sh -c "
        pnpm -w prisma generate &&
        pnpm run dev
      "


volumes:
  node_modules:
  db_data:
networks:
  traefik-network:
    external: true
